distance_threshold: 0.03
evaluation_threshold: 0.02
min_overlapping_percentage: 0.15
target_radius_factor: 2
number_subclouds: 5
size_source: 150
size_target: 2000
refinement_icp_source_size: 1000
refinement_icp_target_size: 5000
min_plane_portion: 0.1
min_plane_distance: 0.04
min_scaling_factor: 0.8
max_scaling_factor: 1.2
max_depth: 3
icp_eps: 1.0e-05
icp_eps2: 1.0e-03
max_icp_it: 300
max_numerical_error: 1.0e-04
max_percentage: 0.85
damping_coefficient: 0.5
delay_factor: 1
remove_plane: 1
max_icp_evaluations: 40
lambda: 1
mu: 0.01
